package chapter3;

public class FibonacciEvenSum
{
	/*Each new term in the Fibonacci sequence is generated by adding the previous two terms.
	  By starting with 1 and 2, the first 10 terms will be:
	  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...	 
	  By considering the terms in the Fibonacci sequence whose values do not exceed
	  four million, find the sum of the even-valued terms. 
	 */
	public static final int MAX_VALUE = 4000000;
	
	public static void main(String[] args)
	{
		//array to store first 40 numbers in the Fibonacci sequence
		int[] FibonacciArray = new int[40];
		int sum = 0;
		
		//first 2 terms are 0 and 1
		FibonacciArray[0] = 0;
		FibonacciArray[1] = 1;
		
		//filling the array
		for(int i = 2; i < FibonacciArray.length; i++ )
			FibonacciArray[i] = FibonacciArray[i - 1] + FibonacciArray[i - 2];
		
		for(int x : FibonacciArray)
			if(x % 2 == 0 && x < MAX_VALUE)
				sum += x;
		
		System.out.println("The sum of the even-valued terms under four million is " + sum + ".");
	}
}
